/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graphic;

import java.awt.Color;
import java.awt.Graphics;


/**
 *
 * @author LENOVO
 */
public class draw_shapes_and_fill_color extends javax.swing.JFrame {

    /**
     * Creates new form draw_shapes_and_fill_color
     */
    public draw_shapes_and_fill_color() {
        initComponents();
        
        
    }
public void paint(Graphics g)
{
    
    //for filled shape
   g.setColor(Color.BLUE);
   g.drawRect(60,60, 300, 200);//fillRect(x,y,width,hight)
   
   //for face
   g.setColor(Color.YELLOW);
   
   g.fillOval(90, 70, 80, 80);//fillOvel(x,y,width,hight)
   
   //g.setColor(Color.black);
   //g.drawOval(90, 70, 80, 80);
   
    //for eyes
   g.setColor(Color.black);
   g.fillOval(110, 95, 10, 10);
   g.fillOval(145, 95, 10, 10);
   
   //for nose
   g.drawLine(130,95,130,115);//drawLine(x1,y1,x2,y2)
   
   
   g.setColor(Color.red);
   
   g.fillArc(113,115,35,20,0,-180);//fillArc(x,y,width,hight,start_angle,end_angle);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(draw_shapes_and_fill_color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(draw_shapes_and_fill_color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(draw_shapes_and_fill_color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(draw_shapes_and_fill_color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new draw_shapes_and_fill_color().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
