/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graphic;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author LENOVO
 */
public class draw_home extends javax.swing.JFrame {

    /**
     * Creates new form draw_home
     */
    public draw_home() {
        initComponents();
    }
    public void paint(Graphics g)
    {
        
        //store x,y coordinates in x[] and y[]
        int x[]={375,275,475};
        int y[]={125,200,200};
        int n=3;//no. of pairs
        
        
        //set gray background for frame
        
        this.setBackground(Color.GRAY);
        
        //set yellow color for rectangle-house
        
        g.setColor(Color.YELLOW);
        g.fillRect(300,200, 150, 100);
        
        //set blue color for another rectangle - door
        
        g.setColor(Color.blue);
        g.fillRect(350, 210, 50, 60);
        
        //draw a line - line below the door
        
        g.drawLine(350, 280, 400, 280);
        
        //set dark gray for polygon -roof
        g.setColor(Color.darkGray);
        g.fillPolygon(x, y, n);
        
        //set cyan color for oval -moon
        
        g.setColor(Color.cyan);
        g.fillOval(100,100, 60, 60);
        
        //set green for arcs -grass
        
        g.setColor(Color.GREEN);
        g.fillArc(50, 250, 150, 100, 0, 180);
        g.fillArc(150, 250, 150, 100, 0, 180);
        
        g.setColor(Color.darkGray);
        g.fillArc(50,257,150,100,0,-180);
        g.fillArc(150,257,150,100,0,-180);
        g.setColor(Color.GREEN);
        
        g.fillArc(450, 250, 150, 100, 0, 180);
        g.setColor(Color.darkGray);
        g.fillArc(450,257,150,100,0,-180);
        
        
        //draw a line - the bottom most line of drawing
        
        g.drawLine(50, 300, 600, 300);
        
        //display some text
        g.setColor(Color.WHITE);
        g.drawString("my happy home",275,350);
   
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(draw_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(draw_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(draw_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(draw_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new draw_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
